// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swjvsakiltyvxlxweiif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3anZzYWtpbHR5dnhseHdlaWlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyOTQyODksImV4cCI6MjA2Nzg3MDI4OX0.hLAHW_p5rUI3l7CYzWRBJ4LKuRWy7QVMBmVosC4S1Ss";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});